version: '3.9'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - environments/.env.local
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # This is for testing purposes only
    volumes:
      - postgres_data:/databases/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - environments/.env.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 