version: '3.9'

services:
  web:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../../environments/.env.local
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
